// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "cc/cc.proto" (package "cc", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * Два параметра name, symbol исключающие друг друга,
 * то есть не может использоваться сразу 2 параметра
 *
 * @generated from protobuf message cc.GetCoinsParams
 */
export interface GetCoinsParams {
    /**
     * @generated from protobuf field: int32 offset = 1;
     */
    offset: number;
    /**
     * @generated from protobuf field: int32 limit = 2;
     */
    limit: number;
    /**
     * @generated from protobuf field: optional string name = 3;
     */
    name?: string; // Для фильтрации по названию
    /**
     * @generated from protobuf field: repeated int32 ids = 4;
     */
    ids: number[]; // Для фильтрации по id
}
/**
 * @generated from protobuf message cc.GetCoinsResponse
 */
export interface GetCoinsResponse {
    /**
     * @generated from protobuf field: uint32 status = 1;
     */
    status: number;
    /**
     * @generated from protobuf field: repeated cc.Coin coins = 2;
     */
    coins: Coin[];
}
/**
 * @generated from protobuf message cc.Coin
 */
export interface Coin {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string symbol = 2;
     */
    symbol: string;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: string icon = 4;
     */
    icon: string;
    /**
     * @generated from protobuf field: float price = 5;
     */
    price: number; // Текущая ценна на данный момент
    /**
     * @generated from protobuf field: float dynamic = 6;
     */
    dynamic: number; // Изменение цены за N времени
}
/**
 * @generated from protobuf message cc.GetCoinParams
 */
export interface GetCoinParams {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number; // Для выборки
}
/**
 * @generated from protobuf message cc.GetCoinResponse
 */
export interface GetCoinResponse {
    /**
     * @generated from protobuf field: uint32 status = 1;
     */
    status: number;
    /**
     * @generated from protobuf field: optional cc.Coin coin = 2;
     */
    coin?: Coin;
}
/**
 * @generated from protobuf message cc.GetValuesParams
 */
export interface GetValuesParams {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number; // Для выборки
}
/**
 * @generated from protobuf message cc.GetValuesResponse
 */
export interface GetValuesResponse {
    /**
     * @generated from protobuf field: uint32 status = 1;
     */
    status: number;
    /**
     * @generated from protobuf field: repeated cc.CoinValue values = 2;
     */
    values: CoinValue[];
}
/**
 * @generated from protobuf message cc.CoinValue
 */
export interface CoinValue {
    /**
     * @generated from protobuf field: float price = 1;
     */
    price: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp date = 2;
     */
    date?: Timestamp;
}
/**
 * @generated from protobuf message cc.GetValuesPerDaysParams
 */
export interface GetValuesPerDaysParams {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number; // Для выборки
    /**
     * @generated from protobuf field: int32 days = 2;
     */
    days: number;
}
/**
 * @generated from protobuf message cc.GetValuesPerDaysResponse
 */
export interface GetValuesPerDaysResponse {
    /**
     * @generated from protobuf field: uint32 status = 1;
     */
    status: number;
    /**
     * @generated from protobuf field: repeated cc.CoinValue values = 2;
     */
    values: CoinValue[];
}
/**
 * @generated from protobuf enum cc.Method
 */
export enum Method {
    /**
     * @generated from protobuf enum value: NULL = 0;
     */
    NULL = 0,
    /**
     * @generated from protobuf enum value: GET_COINS = 1;
     */
    GET_COINS = 1,
    /**
     * @generated from protobuf enum value: GET_COIN = 2;
     */
    GET_COIN = 2,
    /**
     * @generated from protobuf enum value: GET_VALUES_PER_DAY = 3;
     */
    GET_VALUES_PER_DAY = 3,
    /**
     * @generated from protobuf enum value: GET_VALUES_PER_WEEK = 4;
     */
    GET_VALUES_PER_WEEK = 4,
    /**
     * @generated from protobuf enum value: GET_VALUES_PER_MONTH = 5;
     */
    GET_VALUES_PER_MONTH = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class GetCoinsParams$Type extends MessageType<GetCoinsParams> {
    constructor() {
        super("cc.GetCoinsParams", [
            { no: 1, name: "offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "ids", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetCoinsParams>): GetCoinsParams {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.offset = 0;
        message.limit = 0;
        message.ids = [];
        if (value !== undefined)
            reflectionMergePartial<GetCoinsParams>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCoinsParams): GetCoinsParams {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 offset */ 1:
                    message.offset = reader.int32();
                    break;
                case /* int32 limit */ 2:
                    message.limit = reader.int32();
                    break;
                case /* optional string name */ 3:
                    message.name = reader.string();
                    break;
                case /* repeated int32 ids */ 4:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.ids.push(reader.int32());
                    else
                        message.ids.push(reader.int32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCoinsParams, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 offset = 1; */
        if (message.offset !== 0)
            writer.tag(1, WireType.Varint).int32(message.offset);
        /* int32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).int32(message.limit);
        /* optional string name = 3; */
        if (message.name !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* repeated int32 ids = 4; */
        if (message.ids.length) {
            writer.tag(4, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.ids.length; i++)
                writer.int32(message.ids[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cc.GetCoinsParams
 */
export const GetCoinsParams = new GetCoinsParams$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCoinsResponse$Type extends MessageType<GetCoinsResponse> {
    constructor() {
        super("cc.GetCoinsResponse", [
            { no: 1, name: "status", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "coins", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Coin }
        ]);
    }
    create(value?: PartialMessage<GetCoinsResponse>): GetCoinsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.status = 0;
        message.coins = [];
        if (value !== undefined)
            reflectionMergePartial<GetCoinsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCoinsResponse): GetCoinsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 status */ 1:
                    message.status = reader.uint32();
                    break;
                case /* repeated cc.Coin coins */ 2:
                    message.coins.push(Coin.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCoinsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 status = 1; */
        if (message.status !== 0)
            writer.tag(1, WireType.Varint).uint32(message.status);
        /* repeated cc.Coin coins = 2; */
        for (let i = 0; i < message.coins.length; i++)
            Coin.internalBinaryWrite(message.coins[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cc.GetCoinsResponse
 */
export const GetCoinsResponse = new GetCoinsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Coin$Type extends MessageType<Coin> {
    constructor() {
        super("cc.Coin", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "symbol", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "icon", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "price", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 6, name: "dynamic", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<Coin>): Coin {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.symbol = "";
        message.name = "";
        message.icon = "";
        message.price = 0;
        message.dynamic = 0;
        if (value !== undefined)
            reflectionMergePartial<Coin>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Coin): Coin {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string symbol */ 2:
                    message.symbol = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* string icon */ 4:
                    message.icon = reader.string();
                    break;
                case /* float price */ 5:
                    message.price = reader.float();
                    break;
                case /* float dynamic */ 6:
                    message.dynamic = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Coin, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string symbol = 2; */
        if (message.symbol !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.symbol);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* string icon = 4; */
        if (message.icon !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.icon);
        /* float price = 5; */
        if (message.price !== 0)
            writer.tag(5, WireType.Bit32).float(message.price);
        /* float dynamic = 6; */
        if (message.dynamic !== 0)
            writer.tag(6, WireType.Bit32).float(message.dynamic);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cc.Coin
 */
export const Coin = new Coin$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCoinParams$Type extends MessageType<GetCoinParams> {
    constructor() {
        super("cc.GetCoinParams", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetCoinParams>): GetCoinParams {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        if (value !== undefined)
            reflectionMergePartial<GetCoinParams>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCoinParams): GetCoinParams {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCoinParams, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cc.GetCoinParams
 */
export const GetCoinParams = new GetCoinParams$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCoinResponse$Type extends MessageType<GetCoinResponse> {
    constructor() {
        super("cc.GetCoinResponse", [
            { no: 1, name: "status", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "coin", kind: "message", T: () => Coin }
        ]);
    }
    create(value?: PartialMessage<GetCoinResponse>): GetCoinResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.status = 0;
        if (value !== undefined)
            reflectionMergePartial<GetCoinResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCoinResponse): GetCoinResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 status */ 1:
                    message.status = reader.uint32();
                    break;
                case /* optional cc.Coin coin */ 2:
                    message.coin = Coin.internalBinaryRead(reader, reader.uint32(), options, message.coin);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCoinResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 status = 1; */
        if (message.status !== 0)
            writer.tag(1, WireType.Varint).uint32(message.status);
        /* optional cc.Coin coin = 2; */
        if (message.coin)
            Coin.internalBinaryWrite(message.coin, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cc.GetCoinResponse
 */
export const GetCoinResponse = new GetCoinResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetValuesParams$Type extends MessageType<GetValuesParams> {
    constructor() {
        super("cc.GetValuesParams", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetValuesParams>): GetValuesParams {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        if (value !== undefined)
            reflectionMergePartial<GetValuesParams>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetValuesParams): GetValuesParams {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetValuesParams, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cc.GetValuesParams
 */
export const GetValuesParams = new GetValuesParams$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetValuesResponse$Type extends MessageType<GetValuesResponse> {
    constructor() {
        super("cc.GetValuesResponse", [
            { no: 1, name: "status", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "values", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => CoinValue }
        ]);
    }
    create(value?: PartialMessage<GetValuesResponse>): GetValuesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.status = 0;
        message.values = [];
        if (value !== undefined)
            reflectionMergePartial<GetValuesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetValuesResponse): GetValuesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 status */ 1:
                    message.status = reader.uint32();
                    break;
                case /* repeated cc.CoinValue values */ 2:
                    message.values.push(CoinValue.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetValuesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 status = 1; */
        if (message.status !== 0)
            writer.tag(1, WireType.Varint).uint32(message.status);
        /* repeated cc.CoinValue values = 2; */
        for (let i = 0; i < message.values.length; i++)
            CoinValue.internalBinaryWrite(message.values[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cc.GetValuesResponse
 */
export const GetValuesResponse = new GetValuesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CoinValue$Type extends MessageType<CoinValue> {
    constructor() {
        super("cc.CoinValue", [
            { no: 1, name: "price", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 2, name: "date", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<CoinValue>): CoinValue {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.price = 0;
        if (value !== undefined)
            reflectionMergePartial<CoinValue>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CoinValue): CoinValue {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* float price */ 1:
                    message.price = reader.float();
                    break;
                case /* google.protobuf.Timestamp date */ 2:
                    message.date = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.date);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CoinValue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* float price = 1; */
        if (message.price !== 0)
            writer.tag(1, WireType.Bit32).float(message.price);
        /* google.protobuf.Timestamp date = 2; */
        if (message.date)
            Timestamp.internalBinaryWrite(message.date, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cc.CoinValue
 */
export const CoinValue = new CoinValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetValuesPerDaysParams$Type extends MessageType<GetValuesPerDaysParams> {
    constructor() {
        super("cc.GetValuesPerDaysParams", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "days", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetValuesPerDaysParams>): GetValuesPerDaysParams {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.days = 0;
        if (value !== undefined)
            reflectionMergePartial<GetValuesPerDaysParams>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetValuesPerDaysParams): GetValuesPerDaysParams {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* int32 days */ 2:
                    message.days = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetValuesPerDaysParams, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* int32 days = 2; */
        if (message.days !== 0)
            writer.tag(2, WireType.Varint).int32(message.days);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cc.GetValuesPerDaysParams
 */
export const GetValuesPerDaysParams = new GetValuesPerDaysParams$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetValuesPerDaysResponse$Type extends MessageType<GetValuesPerDaysResponse> {
    constructor() {
        super("cc.GetValuesPerDaysResponse", [
            { no: 1, name: "status", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "values", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => CoinValue }
        ]);
    }
    create(value?: PartialMessage<GetValuesPerDaysResponse>): GetValuesPerDaysResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.status = 0;
        message.values = [];
        if (value !== undefined)
            reflectionMergePartial<GetValuesPerDaysResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetValuesPerDaysResponse): GetValuesPerDaysResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 status */ 1:
                    message.status = reader.uint32();
                    break;
                case /* repeated cc.CoinValue values */ 2:
                    message.values.push(CoinValue.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetValuesPerDaysResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 status = 1; */
        if (message.status !== 0)
            writer.tag(1, WireType.Varint).uint32(message.status);
        /* repeated cc.CoinValue values = 2; */
        for (let i = 0; i < message.values.length; i++)
            CoinValue.internalBinaryWrite(message.values[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cc.GetValuesPerDaysResponse
 */
export const GetValuesPerDaysResponse = new GetValuesPerDaysResponse$Type();
/**
 * @generated ServiceType for protobuf service cc.CC
 */
export const CC = new ServiceType("cc.CC", [
    { name: "GetCoins", options: {}, I: GetCoinsParams, O: GetCoinsResponse },
    { name: "GetCoin", options: {}, I: GetCoinParams, O: GetCoinResponse },
    { name: "GetValuesPerDay", options: {}, I: GetValuesParams, O: GetValuesResponse },
    { name: "GetValuesPerWeek", options: {}, I: GetValuesParams, O: GetValuesResponse },
    { name: "GetValuesPerMonth", options: {}, I: GetValuesParams, O: GetValuesResponse }
]);
